modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "durabletools"
version = "${version}"
displayName = "DurableTools"
authors = "shiri47s"
description = '''
Enrich survival by adding durability value to items tools that do not have durability value.
'''
logoFile = "icon.png"

[[dependencies.durabletools]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.durabletools]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.durabletools]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "durabletools.mixins.json"
